name: ollama

x-ollama-base: &ollama-base
  image: docker.io/ollama/ollama:latest
  pull_policy: always
  tty: true
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - app_data:/root/.ollama
  healthcheck:
    test: ["CMD", "ollama", "ps"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
    start_interval: 2s
  labels:
    - com.docker.compose.project=ollama
    - app.name=ollama

x-tailscale-base: &tailscale-base
  image: tailscale/tailscale:latest
  environment:
    - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey --accept-dns --hostname ${ENV_TYPE}ollama${ENV_SUFFIX}
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=false
  volumes:
    - tun_state:/var/lib/tailscale
  devices:
    - /dev/net/tun:/dev/net/tun
  cap_add:
    - NET_ADMIN
  restart: unless-stopped
  secrets:
    - tsauthkey
  healthcheck:
    test: ["CMD", "tailscale", "status"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 10s
    start_interval: 2s
  labels:
    - com.docker.compose.project=ollama
    - app.name=tailscale

services:
  cpu-app:
    <<: *ollama-base
    ports:
      - ${OLLAMA_PORT:-11435}:11434
    runtime: runc
    profiles:
      - loc-cpu
    labels:
      - com.docker.compose.project=ollama
      - app.name=ollama
      - app.mode=loc-cpu

  gpu-app:
    <<: *ollama-base
    ports:
      - ${OLLAMA_PORT:-11435}:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - loc-gpu
    labels:
      - com.docker.compose.project=ollama
      - app.name=ollama
      - app.mode=loc-gpu

  cpu-tail:
    <<: *ollama-base
    network_mode: service:tail-tun
    depends_on:
      tail-tun:
        condition: service_healthy
    runtime: runc
    profiles:
      - cpu-tail
    labels:
      - com.docker.compose.project=ollama
      - app.name=ollama
      - app.mode=cpu-tail

  gpu-tail:
    <<: *ollama-base
    network_mode: service:tail-tun
    depends_on:
      tail-tun:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu-tail
    labels:
      - com.docker.compose.project=ollama
      - app.name=ollama
      - app.mode=gpu-tail

  tail-tun:
    <<: *tailscale-base
    profiles:
      - cpu-tail
      - gpu-tail
    labels:
      - com.docker.compose.project=ollama
      - app.name=tailscale

secrets:
  tsauthkey:
    file: ${TSAUTHKEY_PATH:-./tsauthkey.key}
    external: ${TSAUTHKEY_EXTERNAL:-false}

volumes:
  app_data:
  tun_state: