services:
  engine-local:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ollama-data-local:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 11434:11434
    profiles:
      - local

  engine-chat:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-chat-engine
    pull_policy: always
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    volumes:
      - ollama-data-chat:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: service:tailscale-chat
    profiles:
      - simplechat

  tailscale-chat:
    image: tailscale/tailscale:latest
    container_name: ollama-chat
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey --accept-dns --hostname ollama-chat
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-state-chat:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 11435:11435
    profiles:
      - simplechat

  engine-basic-tool-calling:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-basic-tool-calling-engine
    pull_policy: always
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    volumes:
      - ollama-data-basic-tool-calling:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: service:tailscale-basic-tool-calling
    profiles:
      - basic-tool-calling

  tailscale-basic-tool-calling:
    image: tailscale/tailscale:latest
    container_name: ollama-tools
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey --accept-dns --hostname ollama-tools
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-state-basic-tool-calling:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 11436:11436
    profiles:
      - basic-tool-calling

  engine-basic:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-basic-engine
    pull_policy: always
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    volumes:
      - ollama-data-basic:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: service:tailscale-basic
    profiles:
      - generic

  tailscale-basic:
    image: tailscale/tailscale:latest
    container_name: ollama-basic
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey --accept-dns --hostname ollama-basic
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-state-basic:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 11437:11437
    profiles:
      - generic

  engine-complex:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-complex-engine
    pull_policy: always
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    volumes:
      - ollama-data-complex:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: service:tailscale-complex
    profiles:
      - complex

  tailscale-complex:
    image: tailscale/tailscale:latest
    container_name: ollama-complex
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey --accept-dns --hostname ollama-complex
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-state-complex:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 11438:11438
    profiles:
      - complex

secrets:
  tsauthkey:
    file: ~/.secrets/tsauthkey-tag-llm.key

volumes:
  ollama-data-local:
  ollama-data-chat:
  ollama-data-basic-tool-calling:
  ollama-data-basic:
  ollama-data-complex:
  tailscale-state-local:
  tailscale-state-chat:
  tailscale-state-basic-tool-calling:
  tailscale-state-basic:
  tailscale-state-complex: